name: coresys
main: pawarenessc\coresys\Main
version: 4
api: [4.0.0,3.0.0,3.5.0]
author : PawarenessC
load: POSTWORLD
description: play pvp.
commands:
 core:
  description: "PvPに参加"
  usage: " /core "
